CREATE TABLE IF NOT EXISTS `mydb`.`Alumno` (
  `CD_CUENTA` INT NOT NULL,
  `NB_PATERNO` VARCHAR(20) NOT NULL,
  `NB_MATERNO` VARCHAR(20) NOT NULL,
  `NB_NOMBRE` VARCHAR(20) NOT NULL,
  `NB_NOMBRE2` VARCHAR(20) NOT NULL,
  `ST_ACTIVO` VARCHAR(1) NOT NULL,
  `NU_PRESTAMOS` INT(1) NOT NULL,
  PRIMARY KEY (`CD_CUENTA`));


CREATE TABLE IF NOT EXISTS `mydb`.`LIBRO` (
  `cd_LIBRO` VARCHAR(15) NOT NULL,
  `NB_AUTOR` VARCHAR(45) NOT NULL,
  `NB_TITULO` VARCHAR(45) NOT NULL,
  `NU_PAGINAS` INT(4) NOT NULL,
  `NB_EDITORIAL` VARCHAR(45) NOT NULL,
  `NU_ALMACEN` VARCHAR(45) NOT NULL,
  `PRESTAMO_CD_PRESTAMO` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`cd_LIBRO`, `PRESTAMO_CD_PRESTAMO`),
  INDEX `fk_LIBRO_PRESTAMO_idx` (`PRESTAMO_CD_PRESTAMO` ASC) VISIBLE,
  CONSTRAINT `fk_LIBRO_PRESTAMO`
    FOREIGN KEY (`PRESTAMO_CD_PRESTAMO`)
    REFERENCES `mydb`.`PRESTAMO` (`CD_PRESTAMO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);
    
    CREATE TABLE IF NOT EXISTS `mydb`.`LIBRO` (
  `cd_LIBRO` VARCHAR(15) NOT NULL,
  `NB_AUTOR` VARCHAR(45) NOT NULL,
  `NB_TITULO` VARCHAR(45) NOT NULL,
  `NU_PAGINAS` INT(4) NOT NULL,
  `NB_EDITORIAL` VARCHAR(45) NOT NULL,
  `NU_ALMACEN` VARCHAR(45) NOT NULL,
  `PRESTAMO_CD_PRESTAMO` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`cd_LIBRO`, `PRESTAMO_CD_PRESTAMO`),
  INDEX `fk_LIBRO_PRESTAMO_idx` (`PRESTAMO_CD_PRESTAMO` ASC) VISIBLE,
  CONSTRAINT `fk_LIBRO_PRESTAMO`
    FOREIGN KEY (`PRESTAMO_CD_PRESTAMO`)
    REFERENCES `mydb`.`PRESTAMO` (`CD_PRESTAMO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);
    